#!/bin/sh

guess_java_home() {
    if test "a$JAVA_HOME" = "a"; then
	JAVACMD=${JAVACMD:-`which java`}
	JAVACMD=`readlink -f $JAVACMD`

	JAVA_HOME=${JAVACMD%%/jre/bin/java}
	JAVA_HOME=${JAVA_HOME%%/bin/java}
    fi
}

AJPATH=/usr/share/java/aspectjtools.jar

guess_java_home

TOOLS_JAR="$JAVA_HOME/lib/tools.jar"

exec "$JAVACMD" -classpath "$AJPATH:$TOOLS_JAR${CLASSPATH:+:$CLASSPATH}" \
  ${JAVA_OPTS:=-Xmx64M} \
  org.aspectj.tools.ajdoc.Main "$@"
